CRW-3137, updating with changes for building in cachito.
redhat-developer/devspaces-images pull request #326
Opened 2022-09-16 23:03 UTC by SDawley

Updating with the changes that worked in my devel branch. Technically bootstrap.Dockerfile isn't needed anymore but I've left it since it might be useful to anyone who wants to build locally.

2022-09-18 21:21 UTC, nickboldt commented on devspaces-imagepuller/get-sources.sh
> -if [[ ${PULL_ASSETS} -eq 1 ]]; then
I guess on lines 12 and 16 you don't need PULL_ASSETS anymore. Should the `-p` flag exit 0 now?

2022-09-18 21:24 UTC, nickboldt commented
If someone wants to build locally, can they use this?
```
docker build -t ${DOCKERIMAGE_NAME}:${DOCKERIMAGE_TAG} -f ./docker/Dockerfile .
```
(As seen on https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/devspaces-imagepuller#manual  ) 

And if so, is bootstrap.Dockerfile therefore obsolete?

2022-09-19 19:15 UTC, SDawley commented
I forgot the docker folder existed. bootstrap.Dockerfile is removed.

2022-09-19 20:03 UTC, nickboldt commented
In sync.sh we're still creating the bootstrap.Dockerfile (lines 74-75)
```
# use upstream dockerfile as bootstrap one (to retrieve dependencies for offline build)
cp ${SOURCEDIR}/docker/Dockerfile ${TARGETDIR}/bootstrap.Dockerfile
```

2022-09-19 20:05 UTC, nickboldt requested changes
In sync.sh we're still creating the bootstrap.Dockerfile (lines 74-75)
```
# use upstream dockerfile as bootstrap one (to retrieve dependencies for offline build)
cp ${SOURCEDIR}/docker/Dockerfile ${TARGETDIR}/bootstrap.Dockerfile
```

Also if I compare traefik's get-sources.sh vs. this one, I see some other leftovers...

![image](https://user-images.githubusercontent.com/227597/191106716-f38d1309-5507-46dd-9680-cd8ba2f50ce2.png)

2022-09-19 21:02 UTC, merged