CRW-3138: Update Opertator to use Cachito
redhat-developer/devspaces-images pull request #344
Opened 2022-11-02 23:56 UTC by SDawley

Add new dockerfile for brew and update sync to use that.
Update container.yaml with additional sources.

2022-11-03 16:10 UTC, nickboldt requested changes
Does a change need to happen in ./build/scripts/util.sh too? it's called by ./get-sources.sh and ./build/scripts/sync.sh and defines a method `updateDockerfileArgs` that updates the Dockerfile...

2022-11-03 22:41 UTC, SDawley commented
> Does a change need to happen in ./build/scripts/util.sh too? it's called by ./get-sources.sh and ./build/scripts/sync.sh and defines a method `updateDockerfileArgs` that updates the Dockerfile...

get-sources no longer references util.sh and updateDockerfileArgs isn't called by sync.sh anymore as the versions are defined in job-config.json so I can probably remove the script entirely.

2022-11-03 22:43 UTC, nickboldt commented
>  probably remove the script entirely

as long as nothing else uses it, then yeah. Simplication!

2022-11-07 16:14 UTC, nickboldt approved these changes

2022-11-07 16:14 UTC, merged